version: "3.3"

networks:
  traefik-public:
    external: true

services:
  web:
    image: accessv2-master_web:latest
    build:
      context: ./image
      dockerfile: Dockerfile
    networks:
      - traefik-public
    environment:
      - DB_HOST=db
      - DB_USER=access
      - DB_PASSWORD=
      - DB_DB=access
    volumes:
      - access_html:/var/www/html/:ro
   
  db:
    image: mariadb:latest
    networks:
      - traefik-public
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_DATABASE=access
      - MARIADB_USER=access
      - MARIADB_PASSWORD=
    volumes:
      - access_db:/var/lib/mysql
    
volumes:
  access_db:
  access_html:
