name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: bash
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_API_KEY}}
          REPO: ${{github.repository}}
        run: curl --location --request GET "https://deploy2.secuso.org/api/repo/$REPO?rebuild&update&restart&branch=master" --form "API_KEY=$DEPLOY_KEY"
